### ISSUE TITLE
Publish the package on NPM

### ISSUE THREAD

**Issue by olivierlemasle** [nullivex/angular-socket.io-mock#11]
Hi,

Do you plan publishing this package on NPM?
That would be great!

Thanks!

**Comment by nullivex** [comment]
Yes I can do that.

**Comment by philhudson91** [comment]
+1 for this, has it been published yet please?

**Comment by Doginal** [comment]
+1

**Comment by nullivex** [comment]
This is completed as of 1.2.0 sorry for the delay. We have formed an official consortium to help with maintenance.

Please check out https://www.nullivex.com and join us on the forums.

Thanks

**Comment by nullivex** [comment]
Confirming the package is released here: https://www.npmjs.com/package/angular-socket.io-mock
