### ISSUE TITLE
Not able to inject the dependency '_notify_'

### ISSUE THREAD

**Issue by devendiran** [nullivex/angular-socket.io-mock#12]
Hi it's not issue but i incurred with socket.io testing jasmine. 

Here iam facing an issue with dependency injection **Unknown provider: notifyProvider <- notify** 

Could you help me on this ?

**Comment by nullivex** [comment]
Hello,

Personally I havent used this package in much time but I am looking to make new  releases. If you can help debug the issue I would be happy to accept a pull request.

Thanks
