### ISSUE TITLE
es6 imports - trying to have same code in production and testing phase

### ISSUE THREAD

**Issue by djindjic** [nullivex/angular-socket.io-mock#9]
is it possible to have `import 'btford/angular-socket-io';` in my production code, but just somehow 'override' it in specs by `import 'nullivex/angular-socket.io-mock';` without comment my first import?

btw everything else work fine for me, thanks!

**Comment by djindjic** [comment]
Sorry, could be that I wasn't clear enough. So, I have an angular module to test, and this module imports `btford/angular-socket-io`. In my karma test, I need to import this module's file, and it pull original imports for this module. In this case `socket-io` and `socket-io-mock` are in collision.

**Comment by nullivex** [comment]
Yea it will collide.

In my environments I used requirejs and loaded the right library depending on the environment.

It depends on how you notify your script that you are testing but you should be able to load the proper module based on the environment.
